name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - name: Start Rust container
        working-directory: /tmp
        run: docker run --detach -v $(pwd):/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER --name rust_dev rust:dev

      - name: Create Rust project
        working-directory: /tmp
        run: docker exec --detach -w /var/rust rust_dev cargo new test

      - name: Permission test
        working-directory: /tmp
        run: |
          pwd
          ls -ld ./
          ls -ld test
          rm -r test
