name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - run: docker run --detach --interactive -v $(pwd):/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER --name rust_dev rust:dev bash
      - run: docker exec --detach -w /var/rust rust_dev cargo new test

      - name: Permission test
        run: |
          pwd
          ls -l ../*
          # ls -ld test
          # rm -r test
