name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - name: Create Rust project
        run: |
          docker run --name rust_dev -dti -v $(pwd)/rust:/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER rust:dev bash
          docker exec -d -w /var/rust -e USER=$USER rust_dev cargo new dummy
          sleep 90
          docker exec -i -w /var/rust rust_dev pwd
          docker exec -i -w /var/rust -e USER=$USER rust_dev ls -lR ./
          pwd
          ls -l $(pwd)/rust
          # ls -ld test
          # rm -r test
