name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v2
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - name: Create Rust project
        uses: actions/checkout@v2
        working-directory: /tmp
        run: docker run --detach -v $(pwd):/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER -w /var/rust rust:dev cargo new test

      - name: Permission test
        uses: actions/checkout@v2
        working-directory: /tmp
        run: |
          pwd
          ls -ld ./
          ls -ld test
          rm -r test
