name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - name: Create project
        run: docker run --rm -v $(pwd)/rust:/var/rust -w /var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER rust:dev cargo new dummy

      - name: Run project
        run: docker run --rm -v $(pwd)/rust:/var/rust -w /var/rust/dummy -u $(id -u $USER):$(id -g $USER) -e USER=$USER rust:dev cargo run

      - name: Project permission test
        run: |
          ls -ld $(pwd)/rust/dummy
          rm -r $(pwd)/rust/dummy
