name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  runs-on: ubuntu-latest
  working-directory: /tmp

jobs:

  build:
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

    - name: Create Rust project
      run: docker run --detach -v $(pwd):/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER -w /var/rust rust:dev cargo new test

    - name: Permission test
      run: |
        pwd
        ls -ld ./
        ls -ld test
        rm -r test
