name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rust_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        run: docker build ./rust --file ./rust/Dockerfile --tag rust:dev

      - name: Create Rust project
        working-directory: /tmp
        run: |
          docker run --name rust_dev --detach -v $(pwd):/var/rust -u $(id -u $USER):$(id -g $USER) -e USER=$USER rust:dev bash
          docker exec -d -w /var/rust rust_dev cargo new test
          sleep 90
          docker exec -d -w /var/rust rust_dev ls -lR
          pwd
          ls -lR ./
          # ls -ld test
          # rm -r test
